Improving Code Maintainability by Using the Diamond Operator in Generic Type Initialization
soen6431group10/robocodeFall2024 pull request #11
Opened 2024-10-13 20:50 UTC by sakshirk

In Java, angular brackets (< and >) are used to define type arguments for generic types, like declaring a list with List<String>. Before Java 7, these type arguments had to be specified explicitly every time generics were used, resulting in redundant code.

Java 7 introduced the diamond operator (<>) to make the code more concise. It allows you to skip the type argument when the compiler can infer it automatically, simplifying the code and reducing verbosity.

However, if the project's Java version (sonar.java.source) is set below 7, this feature is disabled, as the diamond operator is not supported in earlier versions.

2024-10-13 22:03 UTC, 0matleb2 requested changes

2024-10-13 22:03 UTC, 0matleb2 commented on robocode.battle/src/main/java/net/sf/robocode/battle/Battle.java
> +		haltAllRobots();
This PR isn't fixing the mentioned issue, it's only making whitespace changes. Maybe your intended change got lost when resolving a merge conflict?

2024-10-14 20:06 UTC, sakshirk commented on robocode.battle/src/main/java/net/sf/robocode/battle/Battle.java
> +		haltAllRobots();
Yes, while merging the previous code with refactoring my changes were lost. I have corrected the code.

2024-10-14 23:35 UTC, 0matleb2 requested changes

2024-10-14 23:35 UTC, 0matleb2 commented on robocode.battle/src/main/java/net/sf/robocode/battle/Battle.java
> +
Can you revert this whitespace change please? Small things like this can lead to unnecessary merge conflicts.

2024-10-14 23:41 UTC, 0matleb2 requested changes

2024-10-14 23:41 UTC, 0matleb2 commented on robocode.battle/src/main/java/net/sf/robocode/battle/Battle.java
> +                }
This whitespace change too.

2024-10-14 23:48 UTC, sakshirk commented on robocode.battle/src/main/java/net/sf/robocode/battle/Battle.java
> +                }
Corrected

2024-10-14 23:48 UTC, sakshirk commented on robocode.battle/src/main/java/net/sf/robocode/battle/Battle.java
> +
Corrected

2024-10-15 00:01 UTC, 0matleb2 approved these changes

2024-10-15 00:05 UTC, merged