commit
soen6431group10/robocodeFall2024 pull request #5
Opened 2024-10-08 06:18 UTC by Shine-23

2024-10-08 12:28 UTC, 0matleb2 commented
Double check your commits on the PR. It's showing there are no changes.

2024-10-08 12:32 UTC, 0matleb2 commented
Looks like you've referenced the wrong issue in your commits. The issue you should reference is #4.

2024-10-09 16:29 UTC, 0matleb2 requested changes
There are no changes in the PR. Double check your commits @Shine-23.

Also it looks like you references the wrong issue in your commit message and PR title. Should be issue #4.

2024-10-10 01:25 UTC, 0matleb2 requested changes
Extracting the duplicated string used for the XML element name into a constant is a superficial resolution IMO, but one that I'd accept. For me, it points to a need for a much larger scale refactoring to extract classes for reading and writing turn snapshot XML files.

2024-10-10 01:25 UTC, 0matleb2 commented on robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/TurnSnapshot.java
> -			writer.startElement(options.shortAttributes ? "rs" : "robots"); {
The open brace after `writer.startElement()` defines a new scope, but it looks like you've removed it which has an impact on the scope of the variables that were previously in this block. This is a change that isn't related to issue #4 so I'd suggest reverting it.

2024-10-10 01:25 UTC, 0matleb2 commented on robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/TurnSnapshot.java
> +	/** Define a constant for the "robots" literal */
This comment is redundant and can be removed.

2024-10-10 01:25 UTC, 0matleb2 commented on robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/TurnSnapshot.java
> +	private static final String ROBOT = "robots";
I'd suggest a more descriptive variable name.
```suggestion
	private static final String ROBOTS_XML_ELEMENT_NAME = "robots";
```

2024-10-10 01:27 UTC, Shine-23 commented on robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/TurnSnapshot.java
> -			writer.startElement(options.shortAttributes ? "rs" : "robots"); {
If I revert this I'm getting another issue related to this.

2024-10-10 01:31 UTC, 0matleb2 commented on robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/TurnSnapshot.java
> -			writer.startElement(options.shortAttributes ? "rs" : "robots"); {
What issue?

2024-10-10 01:34 UTC, Shine-23 commented on robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/TurnSnapshot.java
> -			writer.startElement(options.shortAttributes ? "rs" : "robots"); {
Something like this "Nested code blocks should not be used"

2024-10-10 01:53 UTC, 0matleb2 commented on robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/TurnSnapshot.java
> -			writer.startElement(options.shortAttributes ? "rs" : "robots"); {
[This one](https://sonarcloud.io/project/issues?open=AZIuy4b_SndwZUJuspPj&id=soen6431group10_robocodeFall2024). It's a separate issue so we shouldn't try to fix it in the same PR as #4.

2024-10-10 01:54 UTC, Shine-23 commented on robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/TurnSnapshot.java
> -			writer.startElement(options.shortAttributes ? "rs" : "robots"); {
Should I revert my changes

2024-10-10 02:03 UTC, 0matleb2 commented on robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/TurnSnapshot.java
> -			writer.startElement(options.shortAttributes ? "rs" : "robots"); {
Yes, revert the changes to the nested code block.

2024-10-10 02:09 UTC, Shine-23 commented on robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/TurnSnapshot.java
> -			writer.startElement(options.shortAttributes ? "rs" : "robots"); {
Once, I revert it back, my sonar analysis is failing and show this issue

2024-10-10 02:14 UTC, 0matleb2 commented on robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/TurnSnapshot.java
> -			writer.startElement(options.shortAttributes ? "rs" : "robots"); {
I marked it as an [accepted issue](https://sonarcloud.io/project/issues?open=AZIuy4b_SndwZUJuspPj&id=soen6431group10_robocodeFall2024) in SonarCloud, to say that it is a valid issue, but will be fixed later. The quality gate code check is now passing!

2024-10-10 02:16 UTC, Shine-23 commented on robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/TurnSnapshot.java
> -			writer.startElement(options.shortAttributes ? "rs" : "robots"); {
ok !

2024-10-10 02:17 UTC, 0matleb2 approved these changes
LGTM! Thanks for the changes @Shine-23.

2024-10-11 18:02 UTC, LeeELIOT approved these changes

2024-10-13 01:35 UTC, sakshirk approved these changes
LGTM!

2024-10-14 23:31 UTC, 0matleb2 requested changes

2024-10-14 23:31 UTC, 0matleb2 commented on robocode.battle/src/main/java/net/sf/robocode/battle/snapshot/TurnSnapshot.java
> +	private static final String  ROBOTS_XML_ELEMENT_NAME_STRING = "robots";
There's a whitespace issue on this line. I also suggest removing "string" from the variable name, it's redundant.

2024-10-15 00:22 UTC, merged