Fix #6:Refactor literal [^0-9.] in Battle.java to reduce its duplication
soen6431group10/robocodeFall2024 pull request #7
Opened 2024-10-09 06:46 UTC by LeeELIOT

# Refactor literal [^0-9.] in Battle.java to reduce its duplication
[GitHub Issue Link](https://github.com/soen6431group10/robocodeFall2024/issues/6)
[SonarCloud Issue Link](https://sonarcloud.io/project/issues?fileUuids=AZIuy3lKSndwZUJusoqZ&issueStatuses=OPEN%2CCONFIRMED&id=soen6431group10_robocodeFall2024&open=AZIuy4cUSndwZUJuspPu&tab=code)

The pull request refactors the literal `[^0-9.]` in Battle.java by define a constant named InvalidCharacter in replace of all the same string. This change aims to avoid duplication and improve project's readability and maintainability.

## Key Changes:

### Extracted Methods:

- **`InvalidCharacter`**: Define a new String constant to store the duplicated string.
- **`[^0-9.]`**: Remove all the redundant and identical string.

## Benefits:

- **Reduced Cognitive Load**: Breaking the method into smaller, focused pieces reduces mental overhead, making the logic easier to follow.
- **Improved Maintainability**: Isolating specific functionality into well-named methods allows for easier updates and modifications in the future.
- **Adherence to Single Responsibility Principle**: Each method is given a distinct, clear responsibility, leading to better organization of the code.

## Conclusion:

This refacoring successfully address duplicated problem of [^0-9.], which improves maintainability and readability.

2024-10-09 16:23 UTC, 0matleb2 commented on robocode.battle/src/main/java/net/sf/robocode/battle/Battle.java
> +					x = Double.parseDouble(coords[0].replaceAll(invalidCharacters, ""));
While this resolves the SQ issue by reusing the regex string, another solution I'd suggest is encapsulating the string replacement behavior into a well name method and reusing that.
```java
private String stripNonNumericCharacters(String input) {
    return input.replaceAll("[^0-9.]", "");
}
```
```suggestion
					x = Double.parseDouble(stripNonNumericCharacters(coords[0]));
```

2024-10-09 16:32 UTC, 0matleb2 requested changes

2024-10-09 16:32 UTC, 0matleb2 commented on .idea/kotlinc.xml
Can you revert these .idea configuration file changes please?

2024-10-09 16:32 UTC, 0matleb2 commented on robocode.battle/src/main/java/net/sf/robocode/battle/Battle.java
> +					x = Double.parseDouble(coords[0].replaceAll(invalidCharacters, ""));
While this resolves the SQ issue by reusing the regex string, another solution I'd suggest is encapsulating the string replacement behavior into a well name method and reusing that.
```java
private String stripNonNumericCharacters(String input) {
    return input.replaceAll("[^0-9.]", "");
}
```
```java
x = Double.parseDouble(stripNonNumericCharacters(coords[0]));
```

2024-10-09 16:40 UTC, LeeELIOT commented on .idea/kotlinc.xml
Sure!

2024-10-09 17:11 UTC, 0matleb2 approved these changes
Thanks for the changes! Approved.

2024-10-10 00:54 UTC, Shine-23 approved these changes
Approved !

2024-10-13 01:33 UTC, sakshirk approved these changes
LGTM!

2024-10-14 13:48 UTC, merged